/* 
    This file was generated by "mtxrun --script "mtx-wtoc.lua" from the metapost cweb 
    files but now maintained as C file.
*/

# include "mpmathinterval.h"

/*tex 
    We don't support the interval number format because we mostly operate in double mode in
    \CONTEXT. It would just be something experimental, like posit.
*/

extern void tex_normal_warning (const char *t, const char *p);

math_data *mp_initialize_interval_math(MP mp)
{
    (void) (mp);
    tex_normal_warning("mplib", "interval mode is not available.");
    return NULL;
}
